# Generated by Django 5.0 on 2023-12-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=100)),
                ('notification_date', models.DateTimeField()),
                ('notification_status', models.CharField(choices=[('seen', 'seen'), ('unseen', 'unseen')], default='unseen', max_length=10)),
            ],
        ),
    ]
