# Generated by Django 5.0 on 2023-12-18 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_user_id_alter_task_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_description2',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
