# Generated by Django 5.0 on 2023-12-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_project_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_description2',
        ),
    ]
